### ISSUE TITLE
Bbb installation 

### ISSUE THREAD

**Issue by Misdaqsyed** [wenlanc/BigBlueButton#1]
Good afternoon
I'm having trouble installing bbb on gibbonedu

First I was getting this error (attached) now I'm getting thia error.
![20230715_160414](https://github.com/wenlanc/BigBlueButton/assets/140418286/a1e539d8-c464-47a8-a908-3cc2ae15197a)

Uncaught Exception: Error - Class "BigBlueButton\Parameters\GetRecordingsParameters" not found in C:\xampp\htdocs\gibbon\modules\BigBlueButton\hook_lessonPlannerView.php on line 116

**Comment by fvlasie** [comment]
Hello Misdaqsyed,

Did you run composer install inside the BigBlueButton module directory?
